//! Embedded provider brand icons for the serve web dashboard.
//!
//! Upstream parity (A3, #2722): icons are served from an embedded `/icons/`
//! route as static brand art — no account data, so no auth; immutable per
//! binary, so aggressively cacheable (`Cache-Control: public, max-age=86400,
//! immutable`, upstream's exact policy). Assets are the pinned upstream SVGs
//! (`upstream v0.48.0: Sources/CodexBar/Resources/ProviderIcon-*.svg`), embedded
//! with `include_bytes!` so the CLI ships as a standalone binary, mirroring
//! upstream's reason for embedding (`CLIServeProviderIcons`).
//! Upstream regenerates its table with `Scripts/generate_serve_provider_icons.py`;
//! this file is regenerated by copying the resources from the upstream tag.

/// Resource name embedded in this binary for `row_id` (a local provider
/// `cli_name`), with dash-normalization for ids that differ from upstream
/// resource naming (`qwen-cloud` → `ProviderIcon-qwencloud`).
/// Unknown names — including pathological ones — yield `None` → 404.
pub fn icon_resource_for(row_id: &str) -> Option<&'static str> {
    let direct = format!("ProviderIcon-{row_id}");
    let normalized = format!("ProviderIcon-{}", row_id.replace('-', ""));
    ICONS
        .binary_search_by_key(&direct.as_str(), |(name, _)| name)
        .or_else(|_| ICONS.binary_search_by_key(&normalized.as_str(), |(name, _)| name))
        .ok()
        .map(|index| ICONS[index].0)
}

/// Look up an embedded icon by resource name (without `.svg`).
/// Unknown names — including pathological ones — yield `None` → 404.
pub fn icon_bytes(resource_name: &str) -> Option<&'static [u8]> {
    ICONS
        .binary_search_by_key(&resource_name, |(name, _)| name)
        .ok()
        .map(|index| ICONS[index].1)
}

/// Local provider-id → icon URL map injected into the page (keys sorted for
/// deterministic, greppable HTML — upstream parity). Only providers whose icon
/// is actually embedded appear; the UI falls back to a neutral dot. Keyed by
/// LOCAL `cli_name`s, so every referenced icon resolves and no dead provider
/// ids leak in.
pub fn icon_url_map() -> String {
    let mut ids: Vec<&str> = crate::core::cli_name_map().keys().copied().collect();
    ids.sort_unstable();
    let mut out = String::from("{");
    let mut first = true;
    for id in ids {
        let Some(resource) = icon_resource_for(id) else {
            continue;
        };
        if !first {
            out.push(',');
        }
        first = false;
        out.push_str(&serde_json::to_string(id).unwrap_or_default());
        out.push(':');
        out.push_str(&serde_json::to_string(&format!("/icons/{resource}.svg")).unwrap_or_default());
    }
    out.push('}');
    out
}

/// Sorted static table (enables binary search). Keep in ASCII order.
static ICONS: &[(&str, &[u8])] = &[
    (
        "ProviderIcon-abacus",
        include_bytes!("icons/ProviderIcon-abacus.svg"),
    ),
    (
        "ProviderIcon-aiand",
        include_bytes!("icons/ProviderIcon-aiand.svg"),
    ),
    (
        "ProviderIcon-alibaba",
        include_bytes!("icons/ProviderIcon-alibaba.svg"),
    ),
    (
        "ProviderIcon-amp",
        include_bytes!("icons/ProviderIcon-amp.svg"),
    ),
    (
        "ProviderIcon-antigravity",
        include_bytes!("icons/ProviderIcon-antigravity.svg"),
    ),
    (
        "ProviderIcon-augment",
        include_bytes!("icons/ProviderIcon-augment.svg"),
    ),
    (
        "ProviderIcon-bedrock",
        include_bytes!("icons/ProviderIcon-bedrock.svg"),
    ),
    (
        "ProviderIcon-chutes",
        include_bytes!("icons/ProviderIcon-chutes.svg"),
    ),
    (
        "ProviderIcon-claude",
        include_bytes!("icons/ProviderIcon-claude.svg"),
    ),
    (
        "ProviderIcon-clinepass",
        include_bytes!("icons/ProviderIcon-clinepass.svg"),
    ),
    (
        "ProviderIcon-codebuff",
        include_bytes!("icons/ProviderIcon-codebuff.svg"),
    ),
    (
        "ProviderIcon-coderabbit",
        include_bytes!("icons/ProviderIcon-coderabbit.svg"),
    ),
    (
        "ProviderIcon-codex",
        include_bytes!("icons/ProviderIcon-codex.svg"),
    ),
    (
        "ProviderIcon-commandcode",
        include_bytes!("icons/ProviderIcon-commandcode.svg"),
    ),
    (
        "ProviderIcon-copilot",
        include_bytes!("icons/ProviderIcon-copilot.svg"),
    ),
    (
        "ProviderIcon-crof",
        include_bytes!("icons/ProviderIcon-crof.svg"),
    ),
    (
        "ProviderIcon-cursor",
        include_bytes!("icons/ProviderIcon-cursor.svg"),
    ),
    (
        "ProviderIcon-deepgram",
        include_bytes!("icons/ProviderIcon-deepgram.svg"),
    ),
    (
        "ProviderIcon-deepinfra",
        include_bytes!("icons/ProviderIcon-deepinfra.svg"),
    ),
    (
        "ProviderIcon-deepseek",
        include_bytes!("icons/ProviderIcon-deepseek.svg"),
    ),
    (
        "ProviderIcon-devin",
        include_bytes!("icons/ProviderIcon-devin.svg"),
    ),
    (
        "ProviderIcon-doubao",
        include_bytes!("icons/ProviderIcon-doubao.svg"),
    ),
    (
        "ProviderIcon-elevenlabs",
        include_bytes!("icons/ProviderIcon-elevenlabs.svg"),
    ),
    (
        "ProviderIcon-factory",
        include_bytes!("icons/ProviderIcon-factory.svg"),
    ),
    (
        "ProviderIcon-gemini",
        include_bytes!("icons/ProviderIcon-gemini.svg"),
    ),
    (
        "ProviderIcon-grok",
        include_bytes!("icons/ProviderIcon-grok.svg"),
    ),
    (
        "ProviderIcon-groq",
        include_bytes!("icons/ProviderIcon-groq.svg"),
    ),
    (
        "ProviderIcon-huggingface",
        include_bytes!("icons/ProviderIcon-huggingface.svg"),
    ),
    (
        "ProviderIcon-jetbrains",
        include_bytes!("icons/ProviderIcon-jetbrains.svg"),
    ),
    (
        "ProviderIcon-kilo",
        include_bytes!("icons/ProviderIcon-kilo.svg"),
    ),
    (
        "ProviderIcon-kimi",
        include_bytes!("icons/ProviderIcon-kimi.svg"),
    ),
    (
        "ProviderIcon-kiro",
        include_bytes!("icons/ProviderIcon-kiro.svg"),
    ),
    (
        "ProviderIcon-litellm",
        include_bytes!("icons/ProviderIcon-litellm.svg"),
    ),
    (
        "ProviderIcon-llmproxy",
        include_bytes!("icons/ProviderIcon-llmproxy.svg"),
    ),
    (
        "ProviderIcon-longcat",
        include_bytes!("icons/ProviderIcon-longcat.svg"),
    ),
    (
        "ProviderIcon-manus",
        include_bytes!("icons/ProviderIcon-manus.svg"),
    ),
    (
        "ProviderIcon-mimo",
        include_bytes!("icons/ProviderIcon-mimo.svg"),
    ),
    (
        "ProviderIcon-minimax",
        include_bytes!("icons/ProviderIcon-minimax.svg"),
    ),
    (
        "ProviderIcon-mistral",
        include_bytes!("icons/ProviderIcon-mistral.svg"),
    ),
    (
        "ProviderIcon-muse",
        include_bytes!("icons/ProviderIcon-muse.svg"),
    ),
    (
        "ProviderIcon-neuralwatt",
        include_bytes!("icons/ProviderIcon-neuralwatt.svg"),
    ),
    (
        "ProviderIcon-notion",
        include_bytes!("icons/ProviderIcon-notion.svg"),
    ),
    (
        "ProviderIcon-nous",
        include_bytes!("icons/ProviderIcon-nous.svg"),
    ),
    (
        "ProviderIcon-ollama",
        include_bytes!("icons/ProviderIcon-ollama.svg"),
    ),
    (
        "ProviderIcon-opencode",
        include_bytes!("icons/ProviderIcon-opencode.svg"),
    ),
    (
        "ProviderIcon-opencodego",
        include_bytes!("icons/ProviderIcon-opencodego.svg"),
    ),
    (
        "ProviderIcon-openrouter",
        include_bytes!("icons/ProviderIcon-openrouter.svg"),
    ),
    (
        "ProviderIcon-perplexity",
        include_bytes!("icons/ProviderIcon-perplexity.svg"),
    ),
    (
        "ProviderIcon-poe",
        include_bytes!("icons/ProviderIcon-poe.svg"),
    ),
    (
        "ProviderIcon-qoder",
        include_bytes!("icons/ProviderIcon-qoder.svg"),
    ),
    (
        "ProviderIcon-qwencloud",
        include_bytes!("icons/ProviderIcon-qwencloud.svg"),
    ),
    (
        "ProviderIcon-replicate",
        include_bytes!("icons/ProviderIcon-replicate.svg"),
    ),
    (
        "ProviderIcon-sakana",
        include_bytes!("icons/ProviderIcon-sakana.svg"),
    ),
    (
        "ProviderIcon-stepfun",
        include_bytes!("icons/ProviderIcon-stepfun.svg"),
    ),
    (
        "ProviderIcon-sub2api",
        include_bytes!("icons/ProviderIcon-sub2api.svg"),
    ),
    (
        "ProviderIcon-t3chat",
        include_bytes!("icons/ProviderIcon-t3chat.svg"),
    ),
    (
        "ProviderIcon-venice",
        include_bytes!("icons/ProviderIcon-venice.svg"),
    ),
    (
        "ProviderIcon-vertexai",
        include_bytes!("icons/ProviderIcon-vertexai.svg"),
    ),
    (
        "ProviderIcon-warp",
        include_bytes!("icons/ProviderIcon-warp.svg"),
    ),
    (
        "ProviderIcon-wayfinder",
        include_bytes!("icons/ProviderIcon-wayfinder.svg"),
    ),
    (
        "ProviderIcon-windsurf",
        include_bytes!("icons/ProviderIcon-windsurf.svg"),
    ),
    (
        "ProviderIcon-xai",
        include_bytes!("icons/ProviderIcon-xai.svg"),
    ),
    (
        "ProviderIcon-zai",
        include_bytes!("icons/ProviderIcon-zai.svg"),
    ),
    (
        "ProviderIcon-zed",
        include_bytes!("icons/ProviderIcon-zed.svg"),
    ),
    (
        "ProviderIcon-zenmux",
        include_bytes!("icons/ProviderIcon-zenmux.svg"),
    ),
    (
        "ProviderIcon-zoommate",
        include_bytes!("icons/ProviderIcon-zoommate.svg"),
    ),
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn icon_table_is_sorted_for_binary_search() {
        let mut sorted = ICONS.iter().map(|(name, _)| *name).collect::<Vec<_>>();
        let original = sorted.clone();
        sorted.sort_unstable();
        assert_eq!(original, sorted, "static table must stay ASCII-sorted");
    }

    #[test]
    fn all_icons_are_valid_utf8_svg() {
        for (name, bytes) in ICONS {
            let text = std::str::from_utf8(bytes).unwrap_or_else(|e| panic!("{name}:{e}"));
            assert!(text.contains("<svg"), "{name}: must be svg markup");
        }
    }

    #[test]
    fn known_icons_are_valid_svg() {
        let bytes = icon_bytes("ProviderIcon-codex").expect("codex icon embedded");
        let text = std::str::from_utf8(bytes).expect("icons are utf-8 svg");
        assert!(text.contains("<svg"), "must be svg markup");
    }

    #[test]
    fn unknown_and_pathological_names_miss() {
        assert!(icon_bytes("ProviderIcon-nope").is_none());
        assert!(icon_bytes("../etc/passwd").is_none());
        assert!(icon_bytes("ProviderIcon-codex.svg").is_none());
        assert!(icon_bytes("").is_none());
    }

    #[test]
    fn icon_url_map_is_sorted_json_of_embedded_only() {
        let map: serde_json::Value = serde_json::from_str(&icon_url_map()).unwrap();
        let obj = map.as_object().unwrap();
        assert_eq!(obj.get("codex").unwrap(), "/icons/ProviderIcon-codex.svg");
        assert_eq!(obj.get("claude").unwrap(), "/icons/ProviderIcon-claude.svg");
        // Dash-normalized local id → upstream resource name.
        assert_eq!(
            obj.get("qwen-cloud").unwrap(),
            "/icons/ProviderIcon-qwencloud.svg"
        );
        assert!(obj.get("openaiapi").is_none(), "no asset -> no entry");
        assert!(obj.get("clawrouter").is_none(), "no such local provider");
        assert!(obj.get("synthetic").is_none(), "no such local provider");
        let keys: Vec<&String> = obj.keys().collect();
        let mut sorted = keys.clone();
        sorted.sort();
        assert_eq!(keys, sorted, "deterministic sorted output");
        // Every mapped key is a real local provider id reachable via the CLI.
        for key in obj.keys() {
            assert!(
                crate::core::cli_name_map().contains_key(key.as_str()),
                "dead provider id leaked into icon map: {key}"
            );
        }
    }

    #[test]
    fn icon_resource_for_normalizes_dash_ids() {
        assert_eq!(
            icon_resource_for("qwen-cloud"),
            Some("ProviderIcon-qwencloud")
        );
        assert_eq!(icon_resource_for("codex"), Some("ProviderIcon-codex"));
        assert!(icon_resource_for("clawrouter").is_none());
        assert!(icon_resource_for("../etc").is_none());
    }
}
