export const TEST_PROVIDER_CATALOG: Array<[string, string]> = [
  ["codex", "Codex"],
  ["claude", "Claude"],
  ["pi", "Pi"],
  ["cursor", "Cursor"],
  ["factory", "Factory"],
  ["gemini", "Gemini"],
  ["antigravity", "Antigravity"],
  ["copilot", "Copilot"],
  ["zai", "z.ai"],
  ["minimax", "MiniMax"],
  ["kiro", "Kiro"],
  ["vertexai", "Vertex AI"],
  ["augment", "Augment"],
  ["opencode", "OpenCode"],
  ["kimi", "Kimi"],
  ["kimik2", "Kimi K2 (removed)"],
  ["amp", "Amp"],
  ["warp", "Warp"],
  ["ollama", "Ollama"],
  ["azureopenai", "Azure OpenAI"],
  ["t3chat", "T3 Chat"],
  ["openrouter", "OpenRouter"],
  ["jetbrains", "JetBrains AI"],
  ["alibaba", "Alibaba"],
  ["alibabatokenplan", "Alibaba Token Plan"],
  ["nanogpt", "NanoGPT"],
  ["infini", "Infini"],
  ["perplexity", "Perplexity"],
  ["abacus", "Abacus AI"],
  ["mistral", "Mistral"],
  ["opencodego", "OpenCode Go"],
  ["kilo", "Kilo"],
  ["bedrock", "AWS Bedrock"],
  ["codebuff", "Codebuff"],
  ["coderabbit", "CodeRabbit"],
  ["deepseek", "DeepSeek"],
  ["deepinfra", "DeepInfra"],
  ["fireworks", "Fireworks"],
  ["aiand", "ai&"],
  ["zenmux", "ZenMux"],
  ["clinepass", "ClinePass"],
  ["longcat", "LongCat"],
  ["neuralwatt", "Neuralwatt"],
  ["zoommate", "ZoomMate"],
  ["windsurf", "Windsurf"],
  ["manus", "Manus"],
  ["mimo", "Xiaomi MiMo"],
  ["doubao", "Doubao"],
  ["commandcode", "Command Code"],
  ["crof", "Crof"],
  ["stepfun", "StepFun"],
  ["venice", "Venice"],
  ["openaiapi", "OpenAI API"],
  ["grok", "Grok"],
  ["elevenlabs", "ElevenLabs"],
  ["deepgram", "Deepgram"],
  ["groq", "Groq"],
  ["huggingface", "Hugging Face"],
  ["helmcode", "Helmcode"],
  ["v0", "v0"],
  ["typesafe", "TypeSafe"],
  ["llmproxy", "LLM Proxy"],
  ["chutes", "Chutes"],
  ["litellm", "LiteLLM"],
  ["poe", "Poe"],
  ["devin", "Devin"],
  ["zed", "Zed"],
  ["crossmodel", "CrossModel (removed)"],
  ["qoder", "Qoder"],
  ["codebuddy", "CodeBuddy"],
  ["sakana", "Sakana AI"],
  ["sub2api", "sub2api"],
  ["qwencloud", "Qwen Cloud"],
  ["notion", "Notion AI"],
  ["replicate", "Replicate"],
  ["meta", "Meta"],
  ["muse", "Muse Code"],
  ["nous", "Nous Portal"],
];
